#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExpandableListViewAnimationExample.Resource", IsApplication=true)]

namespace ExpandableListViewAnimationExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040016
			public const int AnualLeave = 2130968598;
			
			// aapt resource value: 0x7f040002
			public const int BACKGROUNDWHITESMOKE = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int BLACK = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int BLUESKY = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int DARK_GRAY = 2130968589;
			
			// aapt resource value: 0x7f040011
			public const int DIVIDER = 2130968593;
			
			// aapt resource value: 0x7f040019
			public const int Funeral = 2130968601;
			
			// aapt resource value: 0x7f04000b
			public const int HEAVY_GRAY = 2130968587;
			
			// aapt resource value: 0x7f04001b
			public const int HEAVY_RED = 2130968603;
			
			// aapt resource value: 0x7f040008
			public const int LIGHTBLACK = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int LIGHTBLUESKY = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int LIGHTGRAY = 2130968586;
			
			// aapt resource value: 0x7f040024
			public const int LIGHTSILVERGRAY = 2130968612;
			
			// aapt resource value: 0x7f040020
			public const int LIGHTX0_BLUE = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int LIGHTX1_BLUE = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int LIGHTX2_BLUE = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int LIGHTX3_BLUE = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int LIGHT_BLUE = 2130968607;
			
			// aapt resource value: 0x7f040005
			public const int LIGHT_GRAY = 2130968581;
			
			// aapt resource value: 0x7f04001c
			public const int LIGHT_RED = 2130968604;
			
			// aapt resource value: 0x7f040010
			public const int LIGHT_SILVER_GRAY = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int LOGINFILL = 2130968594;
			
			// aapt resource value: 0x7f04001a
			public const int Meternity = 2130968602;
			
			// aapt resource value: 0x7f040014
			public const int Project2 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int Project3 = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int ProjectName1 = 2130968595;
			
			// aapt resource value: 0x7f04001e
			public const int SUPERX1_LIGHT_BLUE = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int SUPER_LIGHT_BLUE = 2130968605;
			
			// aapt resource value: 0x7f04000c
			public const int SUPER_LIGHT_GRAY = 2130968588;
			
			// aapt resource value: 0x7f040017
			public const int SickLeave = 2130968599;
			
			// aapt resource value: 0x7f040000
			public const int TEXTCOLOR = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int TEXTCOLORHINT = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int TRANSPARENT = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int TRANSPARENT_LIGHT_GRAY = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int TRANSPARENT_WHITE = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int WHITE = 2130968579;
			
			// aapt resource value: 0x7f040018
			public const int Wedding = 2130968600;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050017
			public const int CONTENTDETAIL = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int DEFAULTPADDINGLEFTPROFILE = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int DEFAULTPADDINGLEFTTITLEPROFILE = 2131034138;
			
			// aapt resource value: 0x7f050011
			public const int HEADERLOGIN = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int HEIGHTITEMDETAILPROFILE = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int HEIGHTITEMSHADOW = 2131034139;
			
			// aapt resource value: 0x7f05000d
			public const int HEIGHT_BUTTON_CONFIRMDIALOG = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int HEIGHT_BUTTON_RECORDDETAIL = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int HEIGHT_HEADER_CONFIRMDIALOG = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int HEIGHT_IMAGEICON = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int HEIGHT_ITEM_CONFIRMDIALOG = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int MAINTITLEDETAIL = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int MARGINTOP_FRISTITEM = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int MARGINTOP_ITEM = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int MARGIN_RIGHT_BUTTON_CONFIRMDIALOG = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int PADDING_ITEM_CONFIRMDIALOG = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int PADDING_ITEM_RECORDDETAIL = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int SCREEN2_TEXTBOX_HEIGHT = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int TEXTBOX_HEIGHT = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int TEXTSIZE_CONFIRMDIALOG = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int TEXTSIZE_CONFIRMDIALOG_BUTTON = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int TEXTSIZE_CONTENT_BUTTON = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int TEXTSIZE_HEADER_CONFIRMDIALOG = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int TEXTSIZE_RECORDDETAIL = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int TEXTSIZE_RECORDDETAIL_BUTTON = 2131034114;
			
			// aapt resource value: 0x7f050016
			public const int TITLEDETAIL = 2131034134;
			
			// aapt resource value: 0x7f05000b
			public const int WIDTH_BUTTON_CONFIRMDIALOG = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int WIDTH_IMAGEICON = 2131034130;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int ChildControl_ColorProjectsBar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ChildControl_LayoutDescription = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int ChildControl_LayoutHoursSpend = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int ChildControl_txtDescription = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int ChildControl_txtHoursSpend = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int ChildControl_txtProjects = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int GroupControl_Header = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int GroupControl_HoursSpend = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int GroupControl_WrapperLayout = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int expandableListView = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int txtTotalTime = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChildView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GroupView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
